services:
  - type: web
    name: qnpc-auto-news
    env: docker
    plan: free
    region: oregon
    dockerfilePath: Dockerfile
    buildCommand: docker build -t qnpc-auto-news .
    startCommand: docker run -p 10000:10000 qnpc-auto-news
